### ISSUE TITLE
Is this an implementation of FASTSET paper?

### ISSUE THREAD

**Issue by andrewluetgers** [cmather/fast-set#1]
Curious if this is based on [FASTSET: A Fast Data Structure for the Representation of Sets of Integers](https://www.mdpi.com/1999-4893/12/5/91)

**Comment by andrewluetgers** [comment]
HA! Just noticed this code predates that paper. Perhaps an interesting read nonetheless.

**Comment by cmather** [comment]
Hi @andrewluetgers, nice to meet you! A blast from the past as I haven’t looked at this project in quite a while. I was experimenting with various ways to provide fast set operations by using binary arithmetic. I wasn’t referencing a particular paper, although I’m sure there have been many discoveries here before me :). The binary comparisons are interesting because you can determine if something is in one or more states by doing a binary & operation on a state set and a mask. If the result is greater than zero then you have set membership. I believe I was experimenting with this project because I was working on a compiler where I needed a lot of set work. Should note however that I discovered doing binary arithmetic in JavaScript ends up not being super fast! But it was a fun experiment anyway :).

**Comment by andrewluetgers** [comment]
Thanks for the response!
